module.exports = {
  Command: require('./Command'),
  SensorData: require('./SensorData'),
  SensorSnapshot: require('./SensorSnapshot'),
  SensorLog: require('./SensorLog'),
  Alert: require('./Alert'),
  Actuator: require('./Actuator'),
  ActuatorLog: require('./ActuatorLog'),
  ActuatorState: require('./ActuatorState'),
  PendingCommand: require('./PendingCommand'),
  DeviceEvent: require('./DeviceEvent'),
  SoilReading: require('./SoilReading'),
  Settings: require('./Settings'),
  User: require('./User'),
  Device: require('./Device'),
};
